export const SET_PLAYER_ONE_NAME = 'SET_PLAYER_ONE_NAME';
export const SET_PLAYER_TWO_NAME = 'SET_PLAYER_TWO_NAME';
export const SET_PLAYER_THREE_NAME = 'SET_PLAYER_THREE_NAME';
export const SET_PLAYER_FOUR_NAME = 'SET_PLAYER_FOUR_NAME';
export const ADD_ROUND = 'ADD_ROUND';