# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'spades' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spades
  pod 'Firebase/Core'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Google-Mobile-Ads-SDK'

end
